extends: airbnb
parser: babel-eslint
rules:
  no-unused-vars: warn
  react/jsx-filename-extension: off
  react/no-unused-state: warn
  arrow-body-style: off
  prefer-destructuring: warn
  arrow-parens: warn
  jsx-a11y/label-has-for: off