# Generated by Django 2.0.6 on 2018-07-04 02:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('ip_address', models.GenericIPAddressField(unique=True)),
            ],
            options={
                'db_table': 'locks',
            },
        ),
        migrations.CreateModel(
            name='LockPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Lock')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'lock_permissions',
            },
        ),
        migrations.AddField(
            model_name='lock',
            name='allowed_users',
            field=models.ManyToManyField(related_name='allowed_users', through='backend.LockPermissions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lock',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
